import os

def append_switch_css():
    path = r"c:\Users\Cliente\Documents\canchero app\style.css"
    with open(path, 'a', encoding='utf-8') as f:
        f.write("\n\n/* Switch Style */\n")
        f.write(".fs-switch {\n")
        f.write("    position: relative;\n")
        f.write("    display: inline-block;\n")
        f.write("    width: 36px;\n")
        f.write("    height: 20px;\n")
        f.write("    margin-left: 10px;\n")
        f.write("}\n")
        f.write(".fs-switch input {\n")
        f.write("    opacity: 0;\n")
        f.write("    width: 0;\n")
        f.write("    height: 0;\n")
        f.write("}\n")
        f.write(".fs-switch .slider {\n")
        f.write("    position: absolute;\n")
        f.write("    cursor: pointer;\n")
        f.write("    top: 0; left: 0; right: 0; bottom: 0;\n")
        f.write("    background-color: #333;\n")
        f.write("    transition: .4s;\n")
        f.write("    border-radius: 20px;\n")
        f.write("    border: 1px solid var(--border-color);\n")
        f.write("}\n")
        f.write(".fs-switch .slider:before {\n")
        f.write("    position: absolute;\n")
        f.write("    content: '';\n")
        f.write("    height: 14px;\n")
        f.write("    width: 14px;\n")
        f.write("    left: 2px;\n")
        f.write("    bottom: 2px;\n")
        f.write("    background-color: #888;\n")
        f.write("    transition: .4s;\n")
        f.write("    border-radius: 50%;\n")
        f.write("}\n")
        f.write(".fs-switch input:checked + .slider {\n")
        f.write("    background-color: var(--accent);\n")
        f.write("    border-color: var(--accent);\n")
        f.write("}\n")
        f.write(".fs-switch input:checked + .slider:before {\n")
        f.write("    transform: translateX(16px);\n")
        f.write("    background-color: #000;\n")
        f.write("}\n")
    print("style.css updated for fs-switch.")

append_switch_css()
