import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
const URL='https://dofbxgqzcvfjpnvcvdjb.supabase.co';
const SEC=fs.readFileSync(process.env.TEMP+'/sbsec2.txt','utf8').trim();
const PUB='sb_publishable_gPwLXkMHk3HvFz9nm9hgKA_1D0IJBKA';
const admin=createClient(URL,SEC);
const BIZ='qa.negocio.canchero@gmail.com', PASS='QaNegocio2026!';
const ok=(n,v,x='')=>console.log(v?'PASS':'FAIL',n,x);
await admin.auth.admin.createUser({email:BIZ,password:PASS,email_confirm:true}).catch(()=>{});
await admin.from('users').upsert({email:BIZ,name:'QA Complejo',role:'jugador',sub_status:null},{onConflict:'email'});
await admin.from('business_requests').delete().eq('email',BIZ);
await admin.from('business_requests').insert({email:BIZ,name:'QA Complejo',role:'club',status:'APROBADO',approval_code:'CAN-TEST-9999',code_used:false});
const cli=createClient(URL,PUB);
await cli.auth.signInWithPassword({email:BIZ,password:PASS});
const good=await cli.rpc('redeem_business_code',{p_code:'CAN-TEST-9999'});
ok('canjea OK', good.data==='ok', String(good.data||good.error?.message));
const {data:u}=await cli.from('users').select('role,sub_status').eq('email',BIZ).single();
ok('rol pasó a negocio (club)', u && u.role==='club', JSON.stringify(u));
ok('quedó activo', u && u.sub_status==='active');
process.exit(0);
