-- Suscripciones Web Push (una por usuario+endpoint)
create table if not exists push_subscriptions (
  id bigint generated by default as identity primary key,
  user_email text not null,
  endpoint text not null,
  sub_json text not null,
  platform text,
  created_at timestamptz default now(),
  unique (user_email, endpoint)
);
create index if not exists push_subs_email_idx on push_subscriptions (user_email);
