ALTER TABLE public.group_chats ADD COLUMN IF NOT EXISTS match_id UUID;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS home_team TEXT;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS away_team TEXT;
ALTER TABLE public.matches ALTER COLUMN home_team DROP NOT NULL;
ALTER TABLE public.matches ALTER COLUMN away_team DROP NOT NULL;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS scheduled_at TIMESTAMPTZ;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS match_type TEXT DEFAULT 'abierto';
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS slots_total INT DEFAULT 22;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS slots_taken INT DEFAULT 1;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS captain_home_email TEXT;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS captain_away_email TEXT;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS modality TEXT DEFAULT 'abierto';
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'scheduled';
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS rules TEXT;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS formation TEXT DEFAULT '4-3-3';
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS venue_lat DOUBLE PRECISION;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS venue_lng DOUBLE PRECISION;
ALTER TABLE public.match_players ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "open" ON public.match_players;
CREATE POLICY "open" ON public.match_players FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.match_players TO anon, authenticated;
GRANT ALL ON public.matches TO anon, authenticated;
GRANT ALL ON public.group_chats TO anon, authenticated;
GRANT ALL ON public.group_members TO anon, authenticated;
