CREATE TABLE IF NOT EXISTS public.business_requests (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, email TEXT NOT NULL, name TEXT, role TEXT, plan TEXT, sub_type TEXT, status TEXT DEFAULT 'PENDIENTE', account_status TEXT DEFAULT 'pendiente', monthly_price NUMERIC DEFAULT 0, payment_link_mp TEXT, payment_link_stripe TEXT, approval_code TEXT, code_used BOOLEAN DEFAULT false, comprobante_url TEXT, next_payment_date DATE, suspended_at TIMESTAMPTZ, activated_at TIMESTAMPTZ, approved_at TIMESTAMPTZ, trial_ends_at TIMESTAMPTZ, payload JSONB, created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE public.business_requests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "open" ON public.business_requests;
CREATE POLICY "open" ON public.business_requests FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.business_requests TO anon, authenticated;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS is_official BOOLEAN DEFAULT false;
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS official_expires_at TIMESTAMPTZ;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS need_player BOOLEAN DEFAULT false;
ALTER TABLE public.matches ADD COLUMN IF NOT EXISTS format TEXT;
-- RLS permisivo para matches
DROP POLICY IF EXISTS "matches_all" ON public.matches;
CREATE POLICY "matches_all" ON public.matches FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.matches TO anon, authenticated;
DROP POLICY IF EXISTS "match_players_all" ON public.match_players;
CREATE POLICY "match_players_all" ON public.match_players FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.match_players TO anon, authenticated;
-- live_streams table
CREATE TABLE IF NOT EXISTS public.live_streams (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, title TEXT, streamer_email TEXT, team_name TEXT, match_id UUID, formation TEXT DEFAULT '4-3-3', lineup JSONB DEFAULT '[]', status TEXT DEFAULT 'live', chunk_index INT DEFAULT 0, score_home INT DEFAULT 0, score_away INT DEFAULT 0, created_at TIMESTAMPTZ DEFAULT now(), ended_at TIMESTAMPTZ, thumbnail_url TEXT);
ALTER TABLE public.live_streams ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "live_open" ON public.live_streams;
CREATE POLICY "live_open" ON public.live_streams FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.live_streams TO anon, authenticated;
CREATE TABLE IF NOT EXISTS public.business_courts (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, business_email TEXT NOT NULL, name TEXT NOT NULL, type TEXT DEFAULT 'futbol', capacity INT DEFAULT 10, price_per_hour NUMERIC DEFAULT 0, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE public.business_courts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "open" ON public.business_courts;
CREATE POLICY "open" ON public.business_courts FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.business_courts TO anon, authenticated;
CREATE TABLE IF NOT EXISTS public.business_reservations (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, business_email TEXT NOT NULL, court_id UUID, court_name TEXT, client_email TEXT, client_name TEXT, fecha DATE NOT NULL, hora_inicio TIME NOT NULL, hora_fin TIME NOT NULL, precio NUMERIC DEFAULT 0, estado TEXT DEFAULT 'pendiente', comprobante_url TEXT, notas TEXT, created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE public.business_reservations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "open" ON public.business_reservations;
CREATE POLICY "open" ON public.business_reservations FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.business_reservations TO anon, authenticated;
CREATE TABLE IF NOT EXISTS public.business_products (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, business_email TEXT NOT NULL, name TEXT NOT NULL, description TEXT, price NUMERIC DEFAULT 0, stock INT DEFAULT 0, stock_alert INT DEFAULT 5, photo_url TEXT, category TEXT, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE public.business_products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "open" ON public.business_products;
CREATE POLICY "open" ON public.business_products FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.business_products TO anon, authenticated;
CREATE TABLE IF NOT EXISTS public.business_orders (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, business_email TEXT NOT NULL, product_id UUID, product_name TEXT, client_email TEXT, client_name TEXT, cantidad INT DEFAULT 1, precio_total NUMERIC DEFAULT 0, estado TEXT DEFAULT 'pendiente', comprobante_url TEXT, notas TEXT, created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE public.business_orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "open" ON public.business_orders;
CREATE POLICY "open" ON public.business_orders FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.business_orders TO anon, authenticated;
CREATE TABLE IF NOT EXISTS public.business_employees (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, business_email TEXT NOT NULL, employee_email TEXT, employee_name TEXT NOT NULL, role TEXT DEFAULT 'empleado', phone TEXT, notes TEXT, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE public.business_employees ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "open" ON public.business_employees;
CREATE POLICY "open" ON public.business_employees FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.business_employees TO anon, authenticated;
CREATE TABLE IF NOT EXISTS public.business_chatbot_faq (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, business_email TEXT NOT NULL, question TEXT NOT NULL, answer TEXT NOT NULL, order_index INT DEFAULT 0, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE public.business_chatbot_faq ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "open" ON public.business_chatbot_faq;
CREATE POLICY "open" ON public.business_chatbot_faq FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.business_chatbot_faq TO anon, authenticated;
CREATE TABLE IF NOT EXISTS public.business_client_payments (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, business_email TEXT NOT NULL, client_email TEXT, client_name TEXT, amount NUMERIC NOT NULL, concept TEXT, payment_method TEXT DEFAULT 'transferencia', comprobante_url TEXT, estado TEXT DEFAULT 'pendiente', created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE public.business_client_payments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "open" ON public.business_client_payments;
CREATE POLICY "open" ON public.business_client_payments FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.business_client_payments TO anon, authenticated;
CREATE TABLE IF NOT EXISTS public.business_services (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, business_email TEXT NOT NULL, name TEXT NOT NULL, description TEXT, price NUMERIC DEFAULT 0, duration_minutes INT DEFAULT 60, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE public.business_services ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "open" ON public.business_services;
CREATE POLICY "open" ON public.business_services FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.business_services TO anon, authenticated;
CREATE TABLE IF NOT EXISTS public.business_appointments (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, business_email TEXT NOT NULL, service_id UUID, service_name TEXT, client_email TEXT, client_name TEXT, fecha DATE NOT NULL, hora TIME NOT NULL, precio NUMERIC DEFAULT 0, estado TEXT DEFAULT 'pendiente', comprobante_url TEXT, notas TEXT, created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE public.business_appointments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "open" ON public.business_appointments;
CREATE POLICY "open" ON public.business_appointments FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.business_appointments TO anon, authenticated;
CREATE TABLE IF NOT EXISTS public.content_reports (id UUID DEFAULT gen_random_uuid() PRIMARY KEY, reported_by_email TEXT NOT NULL, target_type TEXT NOT NULL, target_id TEXT NOT NULL, target_email TEXT, reason TEXT NOT NULL, status TEXT DEFAULT 'pendiente', admin_note TEXT, created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE public.content_reports ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "open" ON public.content_reports;
CREATE POLICY "open" ON public.content_reports FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON public.content_reports TO anon, authenticated;
